# Generated by Django 3.2.23 on 2023-12-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile_number',
            new_name='mobile_no',
        ),
    ]
