# Generated by Django 3.2.23 on 2024-06-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='User-submitted query.')),
                ('response', models.TextField(blank=True, help_text='Admin response to the query.', null=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the query has been resolved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
