# Generated by Django 3.2.23 on 2024-06-02 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_userquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who raised this query.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
