# Generated by Django 3.2.23 on 2023-12-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.IntegerField(blank=True, null=True)),
                ('is_corner_site', models.BooleanField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=45, null=True)),
                ('facing', models.CharField(blank=True, max_length=45, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=45, null=True)),
                ('plantation', models.CharField(blank=True, max_length=45, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_size', models.PositiveBigIntegerField(default=0)),
                ('area_size_unit', models.IntegerField(blank=True, choices=[(1, 'Sq Ft'), (2, 'Yards'), (3, 'Acres'), (4, 'Guntalu'), (5, 'Cents'), (6, 'Ankanalu')], null=True)),
                ('availability', models.IntegerField(blank=True, choices=[(1, 'Ready'), (2, 'Under Construction'), (3, 'Other')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.IntegerField(choices=[(1, 'DTCP PLOTS'), (2, 'Farmlands'), (3, 'Flat'), (4, 'Villa')])),
                ('area_of_purpose', models.IntegerField(blank=True, choices=[(1, 'Residential'), (2, 'Commercial')], null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dtcp_details', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('phase_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
