# Generated by Django 3.2.23 on 2023-12-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Completed'), (2, 'Not Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='facing',
            field=models.IntegerField(blank=True, choices=[(1, 'North'), (2, 'South'), (3, 'East'), (4, 'West'), (5, 'Northeast'), (6, 'Northwest'), (7, 'Southeast'), (8, 'Southwest')], null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='soil_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Loamy'), (2, 'Clay'), (3, 'Sandy'), (4, 'Peaty'), (5, 'Silty'), (6, 'Chalky'), (7, 'Gravelly')], null=True),
        ),
    ]
