# Generated by Django 3.2.23 on 2024-04-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20240405_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_attractions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq_ft_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
