# Generated by Django 3.2.23 on 2024-04-05 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20240405_1219'),
        ('properties', '0005_auto_20240405_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='current_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='users.customer'),
        ),
    ]
