# Generated by Django 3.2.23 on 2024-04-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20240408_1751'),
        ('properties', '0006_alter_property_current_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='current_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='users.customer'),
        ),
    ]
