# Generated by Django 3.2.23 on 2024-04-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_current_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='amenities',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='property',
            name='dtcp_details',
        ),
        migrations.RemoveField(
            model_name='property',
            name='nearby_attractions',
        ),
        migrations.RemoveField(
            model_name='property',
            name='phase_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='plots_available',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sq_ft_from',
        ),
        migrations.AddField(
            model_name='property',
            name='gmap_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
