# Generated by Django 3.2.23 on 2024-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20240413_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='is_sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
