# Generated by Django 3.2.23 on 2024-05-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_phase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
    ]
