# Generated by Django 3.2.23 on 2024-05-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='is_corner_site',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
