# Generated by Django 3.2.23 on 2024-05-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_plot_area_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='soil_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Red'), (2, 'Loamy'), (3, 'Clay'), (4, 'Sandy'), (5, 'Peaty'), (6, 'Silty'), (7, 'Chalky'), (8, 'Gravelly')], null=True),
        ),
    ]
