# Generated by Django 3.2.23 on 2024-05-07 08:28

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_auto_20240507_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': [django.db.models.expressions.Case(django.db.models.expressions.When(is_slider_image=True, then=django.db.models.expressions.Value(0)), default=django.db.models.expressions.Value(1), output_field=models.IntegerField()), 'slider_image_order'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
