# Generated by Django 3.2.23 on 2024-05-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_propertyimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_thumbnail',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Use as Home screen image'),
        ),
    ]
