# Generated by Django 3.2.23 on 2024-05-24 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_update_updateimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
