# Generated by Django 3.2.23 on 2024-05-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
