# Generated by Django 3.2.23 on 2024-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_auto_20240527_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='amenities_logos/'),
        ),
        migrations.AlterField(
            model_name='nearbyattraction',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='attractions_logos/'),
        ),
    ]
