# Generated by Django 3.2.23 on 2023-12-26 13:46

import app.files.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=app.files.utils.file_generate_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx'])])),
                ('original_file_name', models.TextField()),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('file_type', models.CharField(max_length=255)),
                ('file_usage_type', models.IntegerField(blank=True, choices=[(1, 'Property Image'), (2, 'Property Document'), (3, 'CRM Document'), (4, 'Layout Image')], null=True)),
                ('crm_document_type', models.IntegerField(blank=True, choices=[(1, 'PAN Card'), (2, 'Aadhar Card'), (3, 'Other')], null=True)),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True)),
                ('crm_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm.crmlead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
