# Generated by Django 3.2.23 on 2023-12-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_contact_date', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.IntegerField(blank=True, choices=[(1, 'Site Visit'), (2, 'Token Advance'), (3, 'Documentation'), (4, 'Payment'), (5, 'Document Delivery')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.IntegerField(blank=True, choices=[(1, 'Site Visit'), (2, 'Token Advance'), (3, 'Documentation'), (4, 'Payment'), (5, 'Document Delivery')], null=True)),
                ('new_status', models.IntegerField(blank=True, choices=[(1, 'Site Visit'), (2, 'Token Advance'), (3, 'Documentation'), (4, 'Payment'), (5, 'Document Delivery')], null=True)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.IntegerField(blank=True, choices=[(1, 'Gpay'), (2, 'PayTm')], null=True)),
                ('payment_count', models.IntegerField(default=1)),
                ('payment_status', models.IntegerField(blank=True, choices=[(1, 'Full'), (2, 'Partial')], null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_for', models.IntegerField(blank=True, choices=[(1, 'Token'), (2, 'Visit'), (3, 'Advance'), (4, 'Full Pay')], null=True)),
                ('payment_detail', models.CharField(blank=True, max_length=45, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOfficerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, null=True)),
                ('performance_metrics', models.JSONField(blank=True, null=True)),
                ('evaluation_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pickup', models.BooleanField(default=False)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('is_drop', models.BooleanField(default=False)),
                ('drop_address', models.CharField(blank=True, max_length=45, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_status', models.IntegerField(blank=True, choices=[(1, 'Site Visit'), (2, 'Token Advance'), (3, 'Documentation'), (4, 'Payment'), (5, 'Document Delivery')], null=True)),
                ('approval_status', models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Under Review')], null=True)),
                ('date_requested', models.DateTimeField(blank=True, null=True)),
                ('date_approved_rejected', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
