# Generated by Django 3.2.23 on 2023-12-26 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuschangerequest',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='crm_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmlead'),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='crm_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmlead'),
        ),
        migrations.AddField(
            model_name='salesofficerperformance',
            name='sales_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='crm_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmlead'),
        ),
        migrations.AddField(
            model_name='leadstatuslog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstatuslog',
            name='crm_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.crmlead'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.plot'),
        ),
    ]
