# Generated by Django 3.2.23 on 2023-12-27 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='assigned_so',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_crm_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statuschangerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='statuschangerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
