# Generated by Django 3.2.23 on 2024-04-13 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20240413_1658'),
        ('crm', '0003_auto_20231227_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_detail',
            new_name='payment_description',
        ),
        migrations.RenameField(
            model_name='statuschangerequest',
            old_name='date_approved_rejected',
            new_name='date_approved',
        ),
        migrations.RemoveField(
            model_name='crmlead',
            name='initial_contact_date',
        ),
        migrations.RemoveField(
            model_name='crmlead',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_count',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='sitevisit',
            name='feedback',
        ),
        migrations.AddField(
            model_name='crmlead',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='online_payment_method',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Credit Card'), (2, 'Debit Card'), (3, 'Net Banking'), (4, 'UPI'), (5, 'Razorpay')], null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='online_payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Online'), (2, 'Cash')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statuschangerequest',
            name='date_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_for',
            field=models.IntegerField(choices=[(1, 'Token'), (2, 'Visit'), (3, 'Advance'), (4, 'Full Pay')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='statuschangerequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
