# Generated by Django 3.2.23 on 2024-05-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_plot_is_corner_site'),
        ('crm', '0004_auto_20240413_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.phase'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.plot'),
        ),
    ]
