# Generated by Django 3.2.23 on 2024-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20240502_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crmlead',
            old_name='current_status',
            new_name='current_crm_status',
        ),
        migrations.AddField(
            model_name='crmlead',
            name='current_approval_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Under Review'), (5, 'Completed')], null=True),
        ),
        migrations.AlterField(
            model_name='statuschangerequest',
            name='approval_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Under Review'), (5, 'Completed')], default=1, null=True),
        ),
    ]
