# Generated by Django 3.2.23 on 2024-05-10 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20240510_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='backend_reference_number',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
