# Generated by Django 3.2.23 on 2024-05-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
