# Generated by Django 3.2.23 on 2024-05-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_crmlead_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='crm_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.crmlead'),
        ),
    ]
